// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/applicant/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applicant"
                ],
                "summary": "Get applicant profile",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ApplicantProfile"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applicant"
                ],
                "summary": "Update applicant profile",
                "parameters": [
                    {
                        "description": "Profile payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ApplicantProfile"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/applicant/resume": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applicant"
                ],
                "summary": "Get active resume",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.Resume"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applicant"
                ],
                "summary": "Create or update active resume",
                "parameters": [
                    {
                        "description": "Resume payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.UpsertResumeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.Resume"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/internal/events/user-created": {
            "post": {
                "description": "Temporary HTTP stand-in for RabbitMQ consumer. Remove when real AMQP consumer is wired.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "internal"
                ],
                "summary": "Stub hook for user.created event",
                "parameters": [
                    {
                        "description": "user.created payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.UserCreatedEvent"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_study_jobboard_applicant-service_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_study_jobboard_applicant-service_internal_model.ApplicantProfile": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_study_jobboard_applicant-service_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "profile not found"
                }
            }
        },
        "github_com_study_jobboard_applicant-service_internal_model.Resume": {
            "type": "object",
            "properties": {
                "applicant_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "desired_salary": {
                    "type": "integer"
                },
                "education": {
                    "type": "string"
                },
                "experience_years": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "skills": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_study_jobboard_applicant-service_internal_model.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string",
                    "example": "Backend developer"
                },
                "city": {
                    "type": "string",
                    "example": "Moscow"
                },
                "full_name": {
                    "type": "string",
                    "example": "Ivan Ivanov"
                },
                "phone": {
                    "type": "string",
                    "example": "+79001234567"
                }
            }
        },
        "github_com_study_jobboard_applicant-service_internal_model.UpsertResumeRequest": {
            "type": "object",
            "properties": {
                "desired_salary": {
                    "type": "integer",
                    "example": 150000
                },
                "education": {
                    "type": "string",
                    "example": "BS Computer Science"
                },
                "experience_years": {
                    "type": "integer",
                    "example": 2
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "skills": {
                    "type": "string",
                    "example": "Go, PostgreSQL, RabbitMQ"
                },
                "summary": {
                    "type": "string",
                    "example": "2 years of backend experience"
                },
                "title": {
                    "type": "string",
                    "example": "Go Developer"
                }
            }
        },
        "github_com_study_jobboard_applicant-service_internal_model.UserCreatedEvent": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "event": {
                    "type": "string"
                },
                "occurred_at": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Applicant Service API",
	Description:      "Applicant cabinet microservice (profile + resume).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
